# Generated by Django 5.2.8 on 2025-12-01 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_laudo_modelo', models.CharField(max_length=150, verbose_name='Nome do Laudo')),
            ],
        ),
        migrations.CreateModel(
            name='RedacaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_redacao', models.CharField(help_text='Insira o nome da redação', max_length=150, verbose_name='Nome da Redação')),
                ('texto_redacao', models.TextField(help_text='Insidera o texto modelo da redação, colocando as variáveis no padrão <<NOME_VARIAVEL>>.', verbose_name='Texto da Redação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Setor')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='VariaveisModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variavel', models.CharField(max_length=150, verbose_name='Nome da Variável')),
                ('string_substituicao', models.CharField(max_length=150, verbose_name='String de Substituição')),
                ('tipo_campo', models.CharField(choices=[('Campo Aberto', 'Campo Aberto'), ('Campo Seletor', 'Campo Seletor')], verbose_name='Tipo de Variável')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoRedacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem da Redação')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.laudomodelo')),
                ('redacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.redacaomodelo')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('laudo', 'redacao')},
            },
        ),
        migrations.AddField(
            model_name='laudomodelo',
            name='redacoes_associadas',
            field=models.ManyToManyField(through='a_core.LaudoRedacao', to='a_core.redacaomodelo', verbose_name='Redações Associadas'),
        ),
        migrations.AddField(
            model_name='redacaomodelo',
            name='setor_redacao',
            field=models.ForeignKey(blank=True, help_text='Setor associado à redação.', null=True, on_delete=django.db.models.deletion.CASCADE, to='a_core.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='TopicoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_topico', models.CharField(max_length=150, verbose_name='Nome do Tópico')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8, verbose_name='Status')),
                ('topico_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_core.topicomodelo')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem do Tópico')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.laudomodelo')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.topicomodelo')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('laudo', 'topico')},
            },
        ),
        migrations.AddField(
            model_name='laudomodelo',
            name='topicos_associados',
            field=models.ManyToManyField(through='a_core.LaudoTopico', to='a_core.topicomodelo', verbose_name='Tópicos Associados'),
        ),
        migrations.CreateModel(
            name='TopicoRedacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem da Redação no Tópico')),
                ('redacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.redacaomodelo')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.topicomodelo')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('topico', 'redacao')},
            },
        ),
        migrations.AddField(
            model_name='topicomodelo',
            name='redacoes_associadas',
            field=models.ManyToManyField(through='a_core.TopicoRedacao', to='a_core.redacaomodelo', verbose_name='Redações Associadas'),
        ),
        migrations.CreateModel(
            name='ValorVariavelModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_variavel', models.CharField(verbose_name='Valor da Variável')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8, verbose_name='Status')),
                ('variavel_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_core.variaveismodelo', verbose_name='Variável Associada')),
            ],
        ),
    ]
