# Generated by Django 5.2.8 on 2025-12-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodelo',
            name='redacoes_associadas',
            field=models.ManyToManyField(blank=True, null=True, through='a_core.LaudoRedacao', to='a_core.redacaomodelo', verbose_name='Redações Associadas'),
        ),
    ]
