# Generated by Django 5.2.9 on 2025-12-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_core', '0002_alter_laudomodelo_redacoes_associadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaveismodelo',
            name='laudo_associado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_core.laudomodelo'),
            preserve_default=False,
        ),
    ]
