# Generated by Django 5.2.8 on 2025-12-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_core', '0003_variaveismodelo_laudo_associado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaveismodelo',
            name='tipo_campo',
        ),
    ]
